title: "Hello, world! I'm Anil Shrestha"
description: >
  Write an awesome description for your new site here. 
  It will appear in your document head meta and search results.

permalink: ':title/'

# FIX 1: Baseurl MUST be empty for a primary user site
baseurl: "" 

# FIX 2: This must be your custom domain
url: "https://anilshrestha.name.np" 

# Author Settings
author: Anil Shrestha
author-img: david-freeman.jpg 
about-author: "Hey welcome to my blog, where i write ocassionaly."

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]