title: "Personal blogs"
description: >
 I will write random articles in different technology generally with programming and philsophy

permalink: ':title/'

baseurl: "" 

# FIX 2: This must be your custom domain
url: "https://anilshrestha.name.np" 

# Author Settings
author: Anil Shrestha
author-img: anilshrestha.jpeg 
about-author: "Hey welcome to my personal space"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]